# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_price',
            field=models.FloatField(default=None),
        ),
    ]
